Add account operations and Authorize with security-JWT:Register(don't…
EVOPNU/TandA pull request #3
Opened 2022-02-04 03:24 UTC by EnderWarik

… security),Login(don't security),rename,reemail,repassword,get info by id,get id by token,validation token,+- money(Защекоины)

2022-02-04 15:53 UTC, EvoMGenius commented
Не в мастер ветку. В Dev ветку! Закрой пул и создай новый на ветку дев

2022-02-04 22:40 UTC, EvoMGenius commented
Все, я поменял ветки.

2022-02-04 22:45 UTC, EvoMGenius requested changes

2022-02-04 22:45 UTC, EvoMGenius commented on ControlAccounts/PostModels/LoginE.cs
> +    public class LoginE
В чем отличие от класса Login?

2022-02-04 22:45 UTC, EvoMGenius commented on ControlAccounts/Startup.cs
> +                            ValidateIssuerSigningKey = true,
сколько время жизни токена? где указывается, не тут ли?

2022-02-05 09:12 UTC, EnderWarik commented on ControlAccounts/PostModels/LoginE.cs
> +    public class LoginE
В наличие поля email

2022-02-05 09:13 UTC, EnderWarik commented on ControlAccounts/Startup.cs
> +                            ValidateIssuerSigningKey = true,
не тут. 3600 секунд. 1 час

2022-02-05 09:17 UTC, EvoMGenius requested changes

2022-02-05 09:17 UTC, EvoMGenius commented on ControlAccounts/appsettings.json
> +    "TokenLifeTime": "3600" //1 hour
Исправить на 72 часа

2022-02-20 10:28 UTC, merged